---
title: Sunniesnow
author: UlyssesZhan
timezone: America/Los_Angeles
lang: en-US
description: The web rhythm game
locale: en_US
baseurl: ''
url: https://sunniesnow.github.io
domain: sunniesnow.github.io
logo: /favicon.svg
theme_color: '#ffa520'

markdown: kramdown
kramdown:
  auto_ids: true
defaults:
  - scope:
      path: ''
    values:
      image: /favicon.png
exclude:
  - "**/LICENSE"
  - "**/LICENSE.md"
  - "**/README.md"
  - Gemfile
  - Gemfile.lock
  - "**/.git/"
  - "**/.idea/"
  - ".rubocop.yml"
plugins:
  - jekyll-seo-tag
