---
title: Sunniesnow
author: UlyssesZhan
timezone: America/Los_Angeles
lang: en-US
description: The web rhythm game
locale: en_US
baseurl: ''
url: https://sunniesnow.github.io
domain: sunniesnow.github.io
markdown: kramdown
kramdown:
  auto_ids: true
exclude:
  - "**/LICENSE"
  - "**/LICENSE.md"
  - "**/README.md"
  - Gemfile
  - Gemfile.lock
  - "**/.git/"
  - "**/.idea/"
  - ".rubocop.yml"

